spring:
  datasource:
    url: jdbc:h2:file:${user.dir}/build/test;DB_CLOSE_DELAY=-1;MVCC=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    mapping-resources: classpath:/hibernate/*.hbm.xml
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        #mappingLocations: classpath:/hibernate/*.hbm.xml
        connection:
          poolSize: 1
    show-sql: true
    hibernate:
      ddl-auto: create
  data:
    jpa:
      repositories:
        enabled: true

